package cn.com.aiidc.cms.entity;
// Generated 2017-1-10 17:26:41 by Hibernate Tools 5.1.0.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TRoleRights generated by hbm2java
 */
@Entity
@Table(name = "t_authorities_resources", catalog = "aiidc_cms")
public class TAuthoritiesResources implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	private Integer id;
	private TAuthorities TAuthorities;
	private TResources TResources;

	public TAuthoritiesResources() {
	}

	public TAuthoritiesResources(TAuthorities authorities, TResources resources) {
		this.TAuthorities = authorities;
		this.TResources = resources;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "authority_id")
	public TAuthorities getTAuthorities() {
		return this.TAuthorities;
	}
	public void setTAuthorities(TAuthorities authorities) {
		this.TAuthorities = authorities;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "resource_id")
	public TResources getTResources() {
		return this.TResources;
	}
	public void setTResources(TResources resources) {
		this.TResources = resources;
	}

}
