package cn.com.aiidc.cms.entity;
// Generated 2017-1-9 15:32:23 by Hibernate Tools 5.1.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TDepartment generated by hbm2java
 */
@Entity
@Table(name = "t_department", catalog = "aiidc_cms")
public class TDepartment implements java.io.Serializable {

	private Integer depId;
	private String depName;
	private Integer parentId;
	private String depDescription;
	public TDepartment() {
	}

	public TDepartment(String depName, Integer parentId, String depDescription) {
		this.depName = depName;
		this.parentId = parentId;
		this.depDescription = depDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "dep_id", unique = true, nullable = false)
	public Integer getDepId() {
		return this.depId;
	}

	public void setDepId(Integer depId) {
		this.depId = depId;
	}

	@Column(name = "dep_name", length = 50)
	public String getDepName() {
		return this.depName;
	}

	public void setDepName(String depName) {
		this.depName = depName;
	}

	@Column(name = "parent_id")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "dep_description", length = 100)
	public String getDepDescription() {
		return this.depDescription;
	}

	public void setDepDescription(String depDescription) {
		this.depDescription = depDescription;
	}

}
