package cn.com.aiidc.cms.entity;
// Generated 2017-4-5 20:06:52 by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TResources generated by hbm2java
 */
@Entity
@Table(name = "t_resources", catalog = "aiidc_cms")
public class TResources implements java.io.Serializable
{

    private Integer resourceId;
    private String resourceType;
    private String resourceName;
    private String resourceDesc;
    private String resourcePath;
    private String priority;
    private Byte enable;
    private Byte issys;
    private Integer moduleId;

    public TResources()
    {
    }

    public TResources(String resourceType, String resourceName, String resourceDesc, String resourcePath,
                      String priority, Byte enable, Byte issys, Integer moduleId)
    {
        this.resourceType = resourceType;
        this.resourceName = resourceName;
        this.resourceDesc = resourceDesc;
        this.resourcePath = resourcePath;
        this.priority = priority;
        this.enable = enable;
        this.issys = issys;
        this.moduleId = moduleId;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "resource_id", unique = true, nullable = false)
    public Integer getResourceId()
    {
        return this.resourceId;
    }

    public void setResourceId(Integer resourceId)
    {
        this.resourceId = resourceId;
    }

    @Column(name = "resource_type", length = 100)
    public String getResourceType()
    {
        return this.resourceType;
    }

    public void setResourceType(String resourceType)
    {
        this.resourceType = resourceType;
    }

    @Column(name = "resource_name", length = 100)
    public String getResourceName()
    {
        return this.resourceName;
    }

    public void setResourceName(String resourceName)
    {
        this.resourceName = resourceName;
    }

    @Column(name = "resource_desc", length = 200)
    public String getResourceDesc()
    {
        return this.resourceDesc;
    }

    public void setResourceDesc(String resourceDesc)
    {
        this.resourceDesc = resourceDesc;
    }

    @Column(name = "resource_path", length = 200)
    public String getResourcePath()
    {
        return this.resourcePath;
    }

    public void setResourcePath(String resourcePath)
    {
        this.resourcePath = resourcePath;
    }

    @Column(name = "priority", length = 100)
    public String getPriority()
    {
        return this.priority;
    }

    public void setPriority(String priority)
    {
        this.priority = priority;
    }

    @Column(name = "enable")
    public Byte getEnable()
    {
        return this.enable;
    }

    public void setEnable(Byte enable)
    {
        this.enable = enable;
    }

    @Column(name = "issys")
    public Byte getIssys()
    {
        return this.issys;
    }

    public void setIssys(Byte issys)
    {
        this.issys = issys;
    }

    @Column(name = "module_id")
    public Integer getModuleId()
    {
        return this.moduleId;
    }

    public void setModuleId(Integer moduleId)
    {
        this.moduleId = moduleId;
    }

}
