package cn.com.aiidc.cms.entity;
// Generated 2017-2-26 16:24:29 by Hibernate Tools 5.1.0.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TRole generated by hbm2java
 */
@Entity
@Table(name = "t_role", catalog = "aiidc_cms")
public class TRole implements java.io.Serializable {

	private Integer roleId;
	private String roleName;
	private String roleDescribe;
	private Boolean isValidate;
	private Boolean isSystematic;

	public TRole() {
	}

	public TRole(String roleName, String roleDescribe, Boolean isValidate, Boolean isSystematic) {
		this.roleName = roleName;
		this.roleDescribe = roleDescribe;
		this.isValidate = isValidate;
		this.isSystematic = isSystematic;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "role_id", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_name", length = 20)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "role_describe", length = 200)
	public String getRoleDescribe() {
		return this.roleDescribe;
	}

	public void setRoleDescribe(String roleDescribe) {
		this.roleDescribe = roleDescribe;
	}

	@Column(name = "isValidate")
	public Boolean getIsValidate() {
		return this.isValidate;
	}

	public void setIsValidate(Boolean isValidate) {
		this.isValidate = isValidate;
	}

	@Column(name = "isSystematic")
	public Boolean getIsSystematic() {
		return this.isSystematic;
	}

	public void setIsSystematic(Boolean isSystematic) {
		this.isSystematic = isSystematic;
	}

}
