package cn.com.aiidc.cms.entity;
// Generated 2016-12-29 10:06:34 by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TTable generated by hbm2java
 */
@Entity
@Table(name = "t_table", catalog = "aiidc_cms")
public class TTable implements java.io.Serializable {

	private Integer tableId;
	private String tableName;
	private String iconcls;
	private String func;
	private String action;
	private Integer pid;

	public TTable() {
	}

	public TTable(String tableName, String iconcls, String func, String action, Integer pid) {
		this.tableName = tableName;
		this.iconcls = iconcls;
		this.func = func;
		this.action = action;
		this.pid = pid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "table_id", unique = true, nullable = false)
	public Integer getTableId() {
		return this.tableId;
	}

	public void setTableId(Integer tableId) {
		this.tableId = tableId;
	}

	@Column(name = "table_name", length = 50)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "iconcls", length = 20)
	public String getIconcls() {
		return this.iconcls;
	}

	public void setIconcls(String iconcls) {
		this.iconcls = iconcls;
	}

	@Column(name = "func", length = 20)
	public String getFunc() {
		return this.func;
	}

	public void setFunc(String func) {
		this.func = func;
	}

	@Column(name = "action", length = 20)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "pid")
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

}
