package cn.com.aiidc.cms.entity;
// Generated 2017-1-10 17:26:41 by Hibernate Tools 5.1.0.Final

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TUserRole generated by hbm2java
 */
@Entity
@Table(name = "t_user_role", catalog = "aiidc_cms")
public class TUserRole implements java.io.Serializable {

	private Integer id;
	private TRole TRole;
	private TUser TUser;

	public TUserRole() {
	}

	public TUserRole(TRole TRole, TUser TUser) {
		this.TRole = TRole;
		this.TUser = TUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "role_id")
	public TRole getTRole() {
		return this.TRole;
	}

	public void setTRole(TRole TRole) {
		this.TRole = TRole;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id")
	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

}
